# Generated by Django 4.1.7 on 2023-04-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("players", models.ManyToManyField(to="app.player")),
            ],
        ),
    ]
